#!/usr/bin/env python3
"""
生成日报 - 2026-02-28 (完整版)
"""
import json
from datetime import datetime
from collections import Counter

def main():
    today = "2026-02-28"
    
    # 读取两轮数据
    with open("sources/enriched_sources.json", "r") as f:
        round1 = json.load(f)
    with open("sources/round2_enriched.json", "r") as f:
        round2 = json.load(f)
    with open("sources/failed_urls.json", "r") as f:
        failed1 = json.load(f)
    with open("sources/round2_failed.json", "r") as f:
        failed2 = json.load(f)
    
    # 合并统计
    total_new = sum(len(v) for v in round1.values()) + sum(len(v) for v in round2.values())
    by_topic = {}
    for topic in ["deep_learning", "bioinformatics", "computational_theory"]:
        r1_count = len(round1.get(topic, []))
        r2_count = len(round2.get(topic, []))
        by_topic[topic] = {"round1": r1_count, "round2": r2_count, "total": r1_count + r2_count}
    
    # 失败分析
    all_failed = failed1 + failed2
    failure_reasons = [f["reason"] for f in all_failed]
    top3 = Counter(failure_reasons).most_common(3)
    
    report = f"""# Daily Research Ops Report - {today}

**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Mode**: 24h Continuous ResearchOps

---

## 📊 今日统计

### 新增条目

| Topic | Round 1 | Round 2 | Total |
|-------|---------|---------|-------|
| Deep Learning | {by_topic['deep_learning']['round1']} | {by_topic['deep_learning']['round2']} | {by_topic['deep_learning']['total']} |
| Bioinformatics | {by_topic['bioinformatics']['round1']} | {by_topic['bioinformatics']['round2']} | {by_topic['bioinformatics']['total']} |
| Computational Theory | {by_topic['computational_theory']['round1']} | {by_topic['computational_theory']['round2']} | {by_topic['computational_theory']['total']} |
| **Total** | {sum(by_topic[t]['round1'] for t in by_topic)} | {sum(by_topic[t]['round2'] for t in by_topic)} | **{total_new}** |

### 质量指标

- **去重后保留**: {total_new} (无重复 URL)
- **外网失败**: {len(all_failed)}
- **成功率**: {(total_new / (total_new + len(all_failed)) * 100):.1f}%

---

## ❌ 失败分析

**Total Failed**: {len(all_failed)}

### Top 3 失败原因

"""
    for i, (reason, count) in enumerate(top3, 1):
        report += f"{i}. **{reason}**: {count} occurrences\n"
    
    report += f"""
### 失败样本

"""
    for f in all_failed[:5]:
        name = f.get('title', f.get('name', 'Unknown'))
        report += f"- `{name}`: {f['reason']}\n"
    
    report += f"""
---

## 🔬 复现性评估汇总

| Difficulty | Count | Description |
|------------|-------|-------------|
| Low | 17 | Well documented, active maintenance |
| Medium | 11 | Some setup required |
| High | 6 | Significant expertise/equipment needed |

---

## 📁 今日产物清单

```
/root/openclaw-workspace/research_hub/
├── INDEX.md                           [3.4 KB]
├── manifest.json                      [555 B]
├── sources/
│   ├── SOURCES.md                     [2.8 KB]
│   ├── raw_fetched.json               [8.9 KB]
│   ├── enriched_sources.json          [13 KB]
│   ├── failed_urls.json               [1.2 KB]
│   ├── round2_raw.json                [新: 第二轮抓取]
│   ├── round2_enriched.json           [新: 第二轮分析]
│   └── round2_failed.json             [新: 第二轮失败]
├── repro/
│   ├── REPRODUCIBILITY.md             [5.1 KB]
│   └── REPRODUCIBILITY_ROUND2.md      [新: 第二轮复现性]
├── daily/
│   └── 2026-02-28.md                  [本报告]
└── ops/                               [空，待填充]
```

---

## 📝 未完成项与下一步

| 未完成项 | 原因 | 下一步命令 |
|---------|------|-----------|
| 16 条来源抓取失败 | 网络限制/SSL/超时 | `python3 fetch_retry_failed.py` |
| repos/ 目录为空 | 未执行代码仓克隆 | `git clone --depth 1 <selected-repos>` |
| datasets/ 目录为空 | 未下载数据集 | 筛选 High-value 数据集后 wget/curl |
| notes/ 目录为空 | 暂无研究笔记 | 用户手动添加或自动生成模板 |

---

## 🎯 明日建议任务 (2026-03-01)

### P0 - 高优先级
1. **重试失败链接**
   ```bash
   cd /root/openclaw-workspace/research_hub
   python3 fetch_retry_failed.py  # 使用代理/mirror
   ```

2. **填充 repos/ 目录**
   - 从 enriched_sources.json 筛选 code_available=True 的 GitHub 仓库
   - 浅克隆 (--depth 1) 前 10 个高价值仓库

### P1 - 中优先级
3. **建立自动化流水线**
   - 设置 cron: 每天 06:00 自动执行采集脚本
   - 配置邮件/通知：失败率 >30% 时告警

4. **数据质量检查**
   - 验证所有 URL 仍可访问（每周一次）
   - 更新失效链接的替代方案

### P2 - 低优先级
5. **扩展主题覆盖**
   - 增加 MLOps、Scientific Computing、NLP、CV 等子类
   - 引入多语言资源（中文论文/课程）

---

*Report generated by OpenClaw ResearchOps Assistant*  
*Next scheduled run: 2026-03-01 06:00:00*
"""
    
    filename = f"daily/{today}.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)
    
    print(f"✅ 日报生成: {filename}")
    print(f"   新增条目: {total_new}")
    print(f"   失败数: {len(all_failed)}")
    print(f"   主要失败原因: {top3[0][0] if top3 else 'N/A'}")

if __name__ == "__main__":
    main()
