#!/usr/bin/env python3
"""
生成日报
"""
import json
from datetime import datetime
from collections import Counter

def main():
    today = datetime.now().strftime('%Y-%m-%d')
    
    # 读取数据
    with open("sources/raw_fetched.json", "r") as f:
        raw_data = json.load(f)
    
    with open("sources/failed_urls.json", "r") as f:
        failed = json.load(f)
    
    with open("sources/enriched_sources.json", "r") as f:
        enriched = json.load(f)
    
    # 统计
    total_attempted = sum(len(entries) for entries in raw_data.values())
    total_success = sum(len(entries) for entries in enriched.values())
    total_failed = len(failed)
    
    # 失败原因分析
    failure_reasons = [f["reason"] for f in failed]
    reason_counts = Counter(failure_reasons)
    top3_reasons = reason_counts.most_common(3)
    
    # 可复现性统计
    barrier_dist = {"Low": 0, "Medium": 0, "High": 0, "Unknown": 0}
    for topic_entries in enriched.values():
        for entry in topic_entries:
            barrier = entry["reproducibility"]["run_barrier"]
            if "Low" in barrier and "Medium" not in barrier:
                barrier_dist["Low"] += 1
            elif "High" in barrier:
                barrier_dist["High"] += 1
            elif "Medium" in barrier:
                barrier_dist["Medium"] += 1
            else:
                barrier_dist["Unknown"] += 1
    
    # 生成日报
    report = f"""# Daily Research Ops Report

**Date**: {today}  
**Generated**: {datetime.now().strftime('%H:%M:%S')}

---

## 📊 今日统计

| Metric | Count |
|--------|-------|
| Sources Attempted | {total_attempted} |
| Successfully Fetched | {total_success} |
| Failed | {total_failed} |
| Success Rate | {total_success/total_attempted*100:.1f}% |

### By Topic

| Topic | Success | Notes |
|-------|---------|-------|
| Deep Learning | {len(enriched.get('deep_learning', []))} | PyTorch, ArXiv, MIT course accessible |
| Bioinformatics | {len(enriched.get('bioinformatics', []))} | UniProt, PDB, Bioconductor OK |
| Computational Theory | {len(enriched.get('computational_theory', []))} | Complexity Zoo, TAOCP, Coq OK |

---

## ❌ 失败链接分析

**Total Failed**: {total_failed}

### Top 3 Failure Reasons

"""
    
    for i, (reason, count) in enumerate(top3_reasons, 1):
        report += f"{i}. **{reason}**: {count} occurrences\n"
    
    report += f"\n### Failed URLs List\n\n"
    for f in failed[:5]:  # 只显示前5个
        report += f"- {f['name']}: {f['url']}\n"
    if len(failed) > 5:
        report += f"- ... and {len(failed) - 5} more\n"
    
    report += f"""

---

## 🔬 可复现性评估

| Barrier Level | Count | Description |
|--------------|-------|-------------|
| Low | {barrier_dist['Low']} | Easy to reproduce, well documented |
| Medium | {barrier_dist['Medium']} | Some setup required |
| High | {barrier_dist['High']} | Significant barriers |
| Unknown | {barrier_dist['Unknown']} | Manual review needed |

---

## 📁 今日产物

```
research_hub/
├── INDEX.md                    # Codex-readable index
├── manifest.json               # Machine-readable manifest
├── sources/
│   ├── SOURCES.md              # Human-readable source list
│   ├── raw_fetched.json        # Raw fetch results ({total_attempted} entries)
│   ├── enriched_sources.json   # With reproducibility analysis
│   └── failed_urls.json        # Failed fetches ({total_failed} entries)
└── repro/
    └── REPRODUCIBILITY.md      # Reproducibility report
```

---

## 📝 明日建议任务

### 高优先级
1. **补充失败来源的替代方案**
   - TensorFlow → 尝试 GitHub mirror
   - Hugging Face → 尝试 hf-mirror.com
   - NCBI/Ensembl → 检查是否有 API 限制

2. **扩展资料覆盖**
   - 增加 "MLOps" 类别（模型部署、监控）
   - 增加 "Scientific Computing" 类别（HPC、数值计算）

### 中优先级
3. **完善可复现性信息**
   - 对标记为 "Unknown" 的来源进行人工审核
   - 添加 Docker/conda 环境信息字段

4. **建立自动化更新机制**
   - 设置定时任务检查链接有效性
   - 建立失效链接告警

### 低优先级
5. **优化存储结构**
   - 考虑使用 SQLite 替代 JSON 便于查询
   - 添加全文搜索索引

---

## ⚠️ 已知问题

1. **网络限制**: 部分国外站点访问受限（TensorFlow, Hugging Face）
2. **Rate Limiting**: 某些学术数据库可能有访问频率限制
3. **动态内容**: 部分页面可能需要 JavaScript 渲染才能完整抓取

---

*Report generated by Research Ops Assistant*
"""
    
    filename = f"daily/{today}.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)
    
    print(f"✅ 日报生成完成: {filename}")
    print(f"   新增条目: {total_success}")
    print(f"   失败链接: {total_failed}")
    print(f"   主要失败原因: {top3_reasons[0][0] if top3_reasons else 'N/A'}")

if __name__ == "__main__":
    main()
